name: SQLite - Backup
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  retrieve-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}

      - name: Create backup
        continue-on-error: true
        run: |
          mkdir backup
          cp vendure.sqlite backup/vendure.sqlite
          cp vendure.sqlite-shm backup/vendure.sqlite-shm
          cp vendure.sqlite-wal backup/vendure.sqlite-wal

      - name: Delete branch if exists
        continue-on-error: true
        run: |
          git branch --delete backup

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 'backup'
          create_branch: true
          push_options: '--force'