name: Server - Backup + Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}

      - name: Create backup
        continue-on-error: true
        run: |
          mkdir backup
          cp vendure.sqlite backup/vendure.sqlite
          cp vendure.sqlite-shm backup/vendure.sqlite-shm
          cp vendure.sqlite-wal backup/vendure.sqlite-wal

      - name: Delete branch if exists
        continue-on-error: true
        run: |
          git branch --delete backup

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 'backup'
          create_branch: true
          push_options: '--force'

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: backup
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}

      
      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build

      - name: Copy files to server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          scp -o StrictHostKeyChecking=no -r dist/* ${SSH_USER}@${SSH_HOST}:~/boutique
          sshpass -p ${DIGITALOCEAN_DROPLET_PASSWORD} ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} 'cd boutique && pm2 start index.js --name "boutique"'
