name: Weekly - Backup
on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.REPO }}
          token: ${{ secrets.TOKEN }}

      - name: Copy files from server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PATH: ${{ secrets.SSH_PATH }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p ${SSH_PASSWORD} scp -o StrictHostKeyChecking=no -r ${SSH_USER}@${SSH_HOST}:~/boutique/vendure.sqlite vendure.sqlite
          sshpass -p ${SSH_PASSWORD} scp -o StrictHostKeyChecking=no -r ${SSH_USER}@${SSH_HOST}:~/boutique/vendure.sqlite-shm vendure.sqlite-shm
          sshpass -p ${SSH_PASSWORD} scp -o StrictHostKeyChecking=no -r ${SSH_USER}@${SSH_HOST}:~/boutique/vendure.sqlite-wal vendure.sqlite-wal

      - name: Set backup branch name
        run: |
          export BACKUP_BRANCH_NAME="backup-$(date +"%Y-%m-%d/W%W")"

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ env.BACKUP_BRANCH_NAME }}
          create_branch: true
          push_options: '--force'